name:                zephyr-protolite
version:             0.1.0.0
author:              "Qiu"
maintainer:          "lopi258@outlook.com"
copyright:           "2023 Qiu"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Lightweight generic protobuf en/decoder implementation.
category: Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- bytestring
- utf8-string
- zephyr-binary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Zephyr.ProtoLite
    - Zephyr.ProtoLite.Aliases

tests:
  protolite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zephyr-protolite
    - hspec
    - hspec-expectations
