name:                zephyr-bot
version:             0.1.0.0
github:              "Qiu233/zephyr-bot"
license:             BSD3
author:              "Qiu"
maintainer:          "lopi258@outlook.com"
copyright:           "2023 Qiu"

extra-source-files:
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Haskell re-implementation of QQBot licence.

dependencies:
- base >= 4.7 && < 5
- protolite
- template-haskell
- mtl
- regex
- transformers
- lens
- time
- random
- async
- array
- memory >= 0.18.0
- text
- hashable
- hashmap
- bytestring
- utf8-string
- base64-bytestring
- zlib
- aeson
- aeson-pretty
- cryptonite
- stm
- network
- HsOpenSSL
- http-client
- http-client-tls

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - NoFieldSelectors
    - OverloadedRecordDot
    - DeriveGeneric
    - DuplicateRecordFields
    - TypeApplications

executables:
  zephyr-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zephyr-bot

tests:
  zephyr-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - zephyr-bot