name:                zephyr-bot
version:             0.1.0.0
github:              "githubuser/zephyr-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/zephyr-bot#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- mtl
- transformers
- lens
- time
- random
- async
- array
- text
- hashmap
- bytestring
- utf8-string
- base64-bytestring
- zlib
- aeson
- cryptonite
- proto-lens
- proto-lens-runtime
- stm
- network
- HsOpenSSL
- HTTP

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  zephyr-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zephyr-bot

tests:
  zephyr-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zephyr-bot
